# Generated by Django 5.1.5 on 2025-02-08 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_site', models.CharField(max_length=255)),
                ('slogan', models.CharField(max_length=255)),
                ('endereco', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('redes_sociais', models.JSONField(blank=True, default=dict, verbose_name='Redes Sociais')),
                ('horario_atendimento', models.CharField(blank=True, max_length=100, verbose_name='Horário de Funcionamento')),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
            },
        ),
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=100, verbose_name='Host')),
                ('port', models.IntegerField(verbose_name='Porta')),
                ('username', models.EmailField(max_length=254, verbose_name='Usuário')),
                ('password', models.CharField(max_length=100, verbose_name='Senha')),
                ('email_from', models.EmailField(max_length=254, verbose_name='E-mail de Remessa')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('paypal', 'PayPal'), ('pagseguro', 'PagSeguro'), ('stripe', 'Stripe')], default='paypal', max_length=50, verbose_name='Gateway de pagamento')),
                ('chave_api', models.CharField(max_length=255, verbose_name='Chave API')),
                ('modo_teste', models.BooleanField(default=True, verbose_name='Modo de Teste')),
            ],
        ),
        migrations.CreateModel(
            name='PaginaEstatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('conteudo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
