# Generated by Django 5.1.5 on 2025-02-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(upload_to='produtos/imagens', verbose_name='Imagem do Produto'),
        ),
    ]
