# Generated by Django 5.1.5 on 2025-02-15 07:52

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='produtos/imagens/', variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Imagem do Produto'),
        ),
    ]
