# Generated by Django 5.1.5 on 2025-02-08 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pagamento', models.CharField(choices=[('cartao', 'Cartão de Crédito'), ('boleto', 'Boleto Bancário'), ('pix', 'Pix'), ('debito', 'Cartão de Débito')], max_length=50)),
                ('status_pagamento', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateTimeField(auto_now_add=True)),
                ('transacao_id', models.CharField(max_length=100, unique=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='ordens.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_data', models.JSONField(blank=True, null=True)),
                ('pagamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transacao', to='contas.pagamento')),
            ],
        ),
    ]
